[phases.setup]
nixPkgs = ["nodejs_20", "stockfish"]

[phases.install]
cmds = [
  "npm ci",
  "cd frontend && npm ci"
]

[phases.build]
cmds = [
  "cd frontend && npm run build --configuration production"
]

[start]
cmd = "npm start"
